const projects = [
    {
      id: 0,
      name: "Domek jednorodzinny",
      category: "Dom jednorodzinny",
      area: "140,90",
      storeys: "1",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      image: [
        "./projects/test/Milcz_Tosik_rzut.jpg",
        "./projects/test/Milcz_Tosik_dach.jpg",
        "./projects/test/Milcz_Tosik_elewacje1.jpg",
        "./projects/test/Milcz_Tosik_przekrójAA.jpg",
        "./projects/test/Milcz_Tosik_elewacje2.jpg",
      ],
    },
    {
        id: 1,
        name: "Domek jednorodzinny w X",
        category: "Dom jednorodzinny",
        area: "140,90",
        storeys: "1",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        image: [
          "./projects/test/Milcz_Tosik_rzut.jpg",
          "./projects/test/Milcz_Tosik_dach.jpg",
          "./projects/test/Milcz_Tosik_elewacje1.jpg",
          "./projects/test/Milcz_Tosik_przekrójAA.jpg",
          "./projects/test/Milcz_Tosik_elewacje2.jpg",
        ],
      },
      {
        id: 2,
        name: "Domek jednorodzinny w Y",
        category: "Dom jednorodzinny",
        area: "140,90",
        storeys: "1",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        image: [
          "./projects/test/Milcz_Tosik_rzut.jpg",
          "./projects/test/Milcz_Tosik_dach.jpg",
          "./projects/test/Milcz_Tosik_elewacje1.jpg",
          "./projects/test/Milcz_Tosik_przekrójAA.jpg",
          "./projects/test/Milcz_Tosik_elewacje2.jpg",
        ],
      },
]